#!/usr/bin/env ruby

require "json"
require "uri"
require "net/http"

if ENV['PERSONAL_ACCESS_TOKEN'].nil? || ENV['WORKSPACE_ID'].nil? || ENV['ASSIGNEE'].nil?
  puts "Please set values. / PERSONAL_ACCESS_TOKEN and WORKSPACE_ID and ASSIGNEE'"
  return
end

class Asana

  attr_accessor :personal_access_token, :workspace_id, :assignee

  def initialize
    @personal_access_token = ENV['PERSONAL_ACCESS_TOKEN']
    @workspace_id = ENV['WORKSPACE_ID']
    @assignee = ENV['ASSIGNEE']
  end

  def setup_connection(target, type, request=nil)
    uri = URI.parse("https://app.asana.com/api/1.0/#{target}")
    header = {
      "Content-Type" => "application/json"
    }
    req = eval <<~RUBY
      Net::HTTP::#{type.capitalize}.new(uri, header)
    RUBY
    req.basic_auth(@personal_access_token, '')
    req.body = request.to_json() unless request.nil?
    res = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') { |http| http.request(req) }
    JSON.parse(res.body)
  end
end

asana = Asana.new
argv = ARGV

workspace_id = asana.workspace_id

case argv[0]
when 'hello'
  puts 'Good Morning!'
when 'env'
  puts <<~EOM
    1: #{asana.personal_access_token}
    2: #{asana.workspace_id}
    3: #{asana.assignee}
  EOM
when 'argv'
  puts "$0：#{$0}"

  ARGV.each_with_index do |arg, i|
      puts "ARGV[#{i}]：#{arg}"
  end
when 'projects'
  body = asana.setup_connection("projects", "get")
  unless argv[1].nil?
    ids =  body["data"].map { |project| project['id'] }
    num = argv[1].to_i
    p ids[num]
    if argv[2] == 'tasks'
      body = asana.setup_connection("tasks?project=#{ids[num]}&completed_since=now&limit=100", "get")
      body["data"].map.with_index { |task, index| puts "#{index}: id:#{task['id']} #{task['name']}" }
    end
    return
  end
  body["data"].map.with_index { |project, index| puts "#{index}: id:#{project['id']} #{project['name']}" }
when 'tasks'
  body = asana.setup_connection("tasks?assignee=me&completed_since=now&limit=100&workspace=#{workspace_id}", "get")
  body["data"].map.with_index { |task, index| puts "#{index}: id:#{task['id']} #{task['name']}" }
when 'create'
  if argv[1].nil?
    puts "Please enter [task_name] => '$ asana create [task_name]'"
    return
  end
  request = {
    "data" => {
      "workspace" => "#{workspace_id}",
      "name" => "#{argv[1]}",
      "assignee" => "me"
    }
  }
  body = asana.setup_connection("tasks", "post", request)
  puts "Created Task id:#{body['data']['id']} #{body['data']['name']}"
when 'complete'
  if argv[1].nil?
    puts "Please enter [task_id] => '$ asana complete [task_id]'"
    return
  end
  task_id = argv[1].to_i
  request = {
    "data" => {
      "assignee" => "me",
      "completed" => "true"
    }
  }
  body = asana.setup_connection("tasks/#{task_id}", "put", request)
  puts "Completed Task id:#{body['data']['id']} #{body['data']['name']}"
end
