#!/usr/bin/env ruby

require "json"
require "uri"
require "date"
require "net/http"

if ENV['PERSONAL_ACCESS_TOKEN'].nil? || ENV['WORKSPACE_ID'].nil? || ENV['ASSIGNEE'].nil?
  puts "Please set values. / PERSONAL_ACCESS_TOKEN and WORKSPACE_ID and ASSIGNEE'"
  return
end

class Asana

  attr_accessor :personal_access_token, :workspace_id, :assignee

  def initialize
    @personal_access_token = ENV['PERSONAL_ACCESS_TOKEN']
    @workspace_id = ENV['WORKSPACE_ID']
    @assignee = ENV['ASSIGNEE']
  end

  def setup_connection(target, type, request=nil)
    uri = URI.parse("https://app.asana.com/api/1.0/#{target}")
    header = {
      "Content-Type" => "application/json"
    }
    req = eval <<~RUBY
      Net::HTTP::#{type.capitalize}.new(uri, header)
    RUBY
    req.basic_auth(@personal_access_token, '')
    req.body = request.to_json() unless request.nil?
    res = Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') { |http| http.request(req) }
    JSON.parse(res.body)
  end
end

asana = Asana.new
argv = ARGV

workspace_id = asana.workspace_id

case argv[0]
when 'hello'
  puts 'Good Morning!'
when 'env'
  puts <<~EOM
    1: #{asana.personal_access_token}
    2: #{asana.workspace_id}
    3: #{asana.assignee}
  EOM
when 'argv'
  puts "$0：#{$0}"

  ARGV.each_with_index do |arg, i|
      puts "ARGV[#{i}]：#{arg}"
  end
when 'projects'
  body = asana.setup_connection("projects", "get")
  unless argv[1].nil?
    project_ids =  body["data"].map { |project| project['id'] }
    project_names =  body["data"].map { |project| project['name'] }
    num = argv[1].to_i
    project_id = project_ids[num]
    project_name = project_names[num]
    puts "#{project_name}:"
    case argv[2]
    when 'tasks'
      body = asana.setup_connection("tasks?project=#{project_id}&completed_since=now&limit=100", "get")
      body["data"].map.with_index { |task, index| puts "#{index}: id:#{task['id']} #{task['name']}" }
    when 'create'
      if argv[3].nil?
        puts "Please enter [task_name] => '$ asana projects [num] create [task_name]'"
        return
      end
      request = {
        "data" => {
          "workspace" => "#{workspace_id}",
          "name" => "#{argv[3]}",
          "assignee" => "me"
        }
      }
      body = asana.setup_connection("tasks", "post", request)
      task_id = body['data']['id']
      request = {
        "data" => {
          "project" => "#{project_id}",
        }
      }
      asana.setup_connection("tasks/#{task_id}/addProject", "post", request)
      puts "Created Project[#{project_name}] Task: id:#{body['data']['id']} #{body['data']['name']}"
    end
    return
  end
  body["data"].map.with_index { |project, index| puts "#{index}: id:#{project['id']} #{project['name']}" }
when 'tasks'
  body = asana.setup_connection("tasks?opt_expand=due_on,projects&assignee=me&completed_since=now&limit=100&workspace=#{workspace_id}", "get")
  body["data"].sort_by { |i| i["due_on"].to_i }.each_with_index do |task, index|
    task['due_on'] == Date.today.strftime('%Y-%m-%d') ? due = '[TODAY]' : due = "[#{task['due_on']}]"
    due = nil if due == "[]"
    project = task['projects'] == [] ? 'NO PROJECT' : task['projects'][0]['name']
    puts "#{index}: id:#{task['id']} [#{project}]#{due} #{task['name']}"
  end
when 'create'
  if argv[1].nil?
    puts "CAUTION: Please enter [task_name] => '$ asana create [task_name]'"
    return
  end
  request = {
    "data" => {
      "workspace" => "#{workspace_id}",
      "name" => "#{argv[1]}",
      "assignee" => "me"
    }
  }
  body = asana.setup_connection("tasks", "post", request)
  puts "Created Task: id:#{body['data']['id']} #{body['data']['name']}"
when 'complete'
  if argv[1].nil?
    puts "CAUTION: Please enter [task_id] => '$ asana complete [task_id]'"
    return
  end
  task_id = argv[1].to_i
  request = {
    "data" => {
      "assignee" => "me",
      "completed" => "true"
    }
  }
  body = asana.setup_connection("tasks/#{task_id}", "put", request)
  puts "Completed Task: id:#{body['data']['id']} #{body['data']['name']}"
end
